# Generated by Django 3.2.16 on 2023-11-03 14:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
    ]
